baseURL = 'https://example.org/'
languageCode = 'nl-be'
title = 'Gentse BC'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
    [[menus.main.params]]
      alternativeName = '<span class="fas fa-home"></span><br>'

  [[menus.main]]
    name = 'Clubinfo'
    pageRef = '/'
    weight = 20

  [[menus.main]]
    identifier = 'groepen'
    name = 'Groepen'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    parent = 'groepen'
    name = 'Jeugd'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    parent = 'groepen'
    name = 'Volwassenen'
    pageRef = '/'
    weight = 20

  [[menus.main]]
    parent = 'groepen'
    name = 'Competitie'
    pageRef = '/'
    weight = 30

  [[menus.main]]
    parent = 'groepen'
    name = 'G-bad'
    pageRef = '/'
    weight = 40

  [[menus.main]]
    name = 'Contact'
    pageRef = '/'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
